//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitXMLIntoFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitXMLIntoFiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  files created in
        ///.
        /// </summary>
        internal static string Main_btnSplit_Click_ {
            get {
                return ResourceManager.GetString("Main_btnSplit_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. .
        /// </summary>
        internal static string Main_btnSplit_Click_Done__ {
            get {
                return ResourceManager.GetString("Main_btnSplit_Click_Done__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter split value in MB.
        /// </summary>
        internal static string Main_btnSplit_Click_Enter_split_value_in_MB {
            get {
                return ResourceManager.GetString("Main_btnSplit_Click_Enter_split_value_in_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:
        ///Try to change file size to larger number.
        ///Only found: .
        /// </summary>
        internal static string Main_GetLastNode_ {
            get {
                return ResourceManager.GetString("Main_GetLastNode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  elements.
        /// </summary>
        internal static string Main_GetLastNode__elements {
            get {
                return ResourceManager.GetString("Main_GetLastNode__elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML File to split.
        /// </summary>
        internal static string Main_SplitFile_Select_XML_File_to_split {
            get {
                return ResourceManager.GetString("Main_SplitFile_Select_XML_File_to_split", resourceCulture);
            }
        }
    }
}
